export const signsNumPad = {
  dot: '.',
  zero: '0',
  one: '1',
  two: '2',
  tree: '3',
  four: '4',
  five: '5',
  seven: '7',
  each: '8',
  nine: '9',
  equal: '=',
  plus: '+',
  minus: '\u2212',
  times: '\u00D7',
  division: '\u00F7',
  root: '\u221A',
  expon: 'x\u00B2',
  bs: '\u232B'
}
